### ISSUE TITLE
Use a Relative Path to the Root

### ISSUE THREAD

**Issue by robynmaya** [jefferyclanton/teacozy#2]
https://github.com/jefferyclanton/teacozy/blob/50a6dfe65135c640e0ca13e4a10701330472222b/index.html#L4

Try to just use the relative part to the root - meaning, don't use the period/dot, like so :  `<link href="/resources/css/style.css" rel="stylesheet">` 

This way, you can be sure that you're pointing to the %root%/resources folder. You don't have to keep track of how many subfolders in you are, and calculate the right amount of ../ to traverse your way back to the origin.

**Comment by jefferyclanton** [comment]
When I try href="/resources/css/style.css the css doesn't display. I did find that I can just use href="resources/css/style.css and it displays.
