### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by robynmaya** [jefferyclanton/teacozy#7]
Grade : 👍 But Needs Improvement 

Overall, you did a good job. 

But you need to improve on the way you organize your styling for different elements that will be styled the same way (one class is enough for all of them). Also, familiarize yourself with more HTML5 Semantic elements and don't use Heading elements for content that is not a title/heading or does not have any sub-content. Also try to include your Meta Tags.

For better readability, you may also use /* comments */ in your stylesheet and HTML as a way to signal readers what section that certain parts of your code belongs to.

It also makes more sense to lay your stylesheet out in a way that allows you to quickly find parts of your code. I recommend a top-down format that tackles styles as they appear in the source code. So, an example stylesheet might be ordered like this:

```
/* Universal classes */ 
(body, a, p, h1, etc.)

/* Header */
#header

/* Navigation */ 
#nav-menu

/* Main Content */
#main-content
```

**Comment by jefferyclanton** [comment]
Thank you very much for the feedback. It was very helpful. I am a little confused with the file path issue so I need to do some research to learn about it more. I thank you for calling it to my attention.
